# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ingrese el titulo de la pagina web', max_length=50)),
                ('name', models.CharField(help_text='Ingrese el nombre del cakes que desea', max_length=50)),
                ('kind', models.CharField(help_text='Ingrese el tipo de pastel que desea', max_length=30)),
                ('synopsis', models.CharField(help_text='Pequena resena', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(help_text='Escriba su comentario', max_length=1000)),
                ('pubdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers', models.CharField(help_text='Ingrese el nombre del cliente', max_length=30)),
                ('prices', models.ForeignKey(help_text='Ingrese el precio', on_delete=django.db.models.deletion.CASCADE, to='Cakes.cakes')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='sale',
            field=models.ForeignKey(help_text='seleccione la publicacion', on_delete=django.db.models.deletion.CASCADE, to='Cakes.sale'),
        ),
    ]
